### ISSUE TITLE
The UI management page does not display the blocked IP host

### ISSUE THREAD

**Issue by zqhwsy123** [beefproject/beef#1750]
Zombie hosts have normal access to hook subpages, and UI pages also have log, but do not display hook hosts

**Comment by bcoles** [comment]
I have no idea what you're asking, but maybe this will help:

https://github.com/beefproject/beef/wiki/Configuration

**Comment by zqhwsy123** [comment]
![image](https://user-images.githubusercontent.com/51821343/62002370-30b40d00-b135-11e9-9b05-e8774d42e796.png)

**Comment by zqhwsy123** [comment]
![image](https://user-images.githubusercontent.com/51821343/62002374-47f2fa80-b135-11e9-8270-36e7a718e57a.png)
我用另外的IP访问了勾子网页，这里也有记录，但是在线主机那就是不显示。4.7.0版本可以正常显示

**Comment by zqhwsy123** [comment]
![image](https://user-images.githubusercontent.com/51821343/62002418-247c7f80-b136-11e9-807c-3a50bbe46fae.png)
This is a browser that I use version 4.7.0 to display properly.

**Comment by bcoles** [comment]
The format of the configuration file changed between 0.4.7.x and 0.4.7.4.

You must use an array `[]`.

### < 0.4.7.3

```yaml
    restrictions:
        # subnet of IP addresses that can hook to the framework
        permitted_hooking_subnet: "0.0.0.0/0"
        # subnet of IP addresses that can connect to the admin UI
        #permitted_ui_subnet: "127.0.0.1/32"
        permitted_ui_subnet: "0.0.0.0/0"
```

### 0.4.7.3+

```yaml
    restrictions:
        # subnet of IP addresses that can hook to the framework
        permitted_hooking_subnet: ["0.0.0.0/0", "::/0"]
        # subnet of IP addresses that can connect to the admin UI
        #permitted_ui_subnet: ["127.0.0.1/32", "::1/128"]
        permitted_ui_subnet: ["0.0.0.0/0", "::/0"]
```
