### ISSUE TITLE
Hello, how can we configure BeEF to use HTTPS?

### ISSUE THREAD

**Issue by martinssssssss** [beefproject/beef#1960]
The question is what do we need to do to use BeEF on an HTTPS server?

**Comment by bcoles** [comment]
See the `beef.http.https` section of `config.yaml` :

```yaml
          # Experimental HTTPS support for the hook / admin / all other Thin managed web services
          https:
              enable: true
              # In production environments, be sure to use a valid certificate signed for the value
              # used in beef.http.public (the domain name of the server where you run BeEF)
              key: "beef_key.pem"
              cert: "beef_cert.pem"
```

Note that you may run into issues if running BeEF behind NAT / reverse proxy. #1785
