### ISSUE TITLE
config.yaml can enable priv escalation ??

### ISSUE THREAD

**Issue by begadwael** [beefproject/beef#2246]
I was not able to find my beef creds so I checked out the config.yaml file and it did not need sudo privileges to open 

by running this command gedit /usr/share/beef-xss/config.yaml

![image](https://user-images.githubusercontent.com/56642036/146075658-9963c612-8dea-4d46-85c1-7c0402328da2.png)

in the file it clearly stated my sudo creds which can enable local privilege escalation 

shouldn't that file need sudo privileges to open?

I know that it can be changed but the default password is the devices sudo password (and its stated in clear text in the config file)

**Comment by bcoles** [comment]
Possibly. This is an issue with the `beef-xss` package on your system. The configuration file should not be world readable.

For example, `/etc/beef-xss/config.yaml` appears to be world readable on Kali (albeit a bit out of date).

```
[2021-12-14 15:47:47] root@kali:~/Desktop/metasploit-framework# ls -la  /usr/share/beef-xss/config.yaml
lrwxrwxrwx 1 root root 25 Nov 26 02:49 /usr/share/beef-xss/config.yaml -> /etc/beef-xss/config.yaml
[2021-12-14 15:47:49] root@kali:~/Desktop/metasploit-framework# ls -la /etc/beef-xss/config.yaml
-rw-r--r-- 1 root root 6659 May 29  2019 /etc/beef-xss/config.yaml
```

Knowledge of the password would allow access to the web UI and REST interface.

There's probably a way to privesc this to gain `beef-xss` privileges.

```
[2021-12-14 15:51:56] root@kali:~/Desktop/metasploit-framework# grep User /lib/systemd/system/beef-xss.service
User=beef-xss
```

**Comment by bcoles** [comment]
The `/usr/share/beef-xss` application directory is also world readable.

```
# ls -la /usr/share/ | grep beef
drwxr-xr-x    9 root root   4096 Dec 10 13:56 beef-xss
```

This would allow reading configuration credentials. For example, credentials for the Metasploit extension (not enabled by default) would allow access to `msfrpcd`, which allows code execution by design.

```
# grep metasploit: -A 10 /usr/share/beef-xss/extensions/metasploit/config.yaml 
        metasploit:
            name: 'Metasploit'
            enable: false
            # Metasploit msgrpc connection options
            host: "127.0.0.1"
            port: 55552
            user: "msf"
            pass: "abc123"
            uri: '/api'
            ssl: true
            ssl_version: 'TLS1'
```
