### ISSUE TITLE
Beef portforward

### ISSUE THREAD

**Issue by Kayr123** [beefproject/beef#2545]
Can i use beef with portmap ?

And what is the easiest way ?

DONT CLOSE THIS I WANT PEOPLE OPINIONS.NOT SENDING ME SOME DOCUMENTS .
PLS

**Comment by bcoles** [comment]
> Can i use beef with portmap ?

Presumably you mean portmap.io. I don't see why not.

BeEF is a HTTP server. If portman.io can be used to route HTTP network traffic to your system then yes.

Once you've set up your network routing you will need to change a couple of lines in the config file.

**Comment by Kayr123** [comment]
Ok what should i put here

And tell me what to write in config.yaml

Host
Port
Https . True false
Pls


في الأحد، 14 أوت 2022 12:29 bcoles ***@***.***> كتب:

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by Kayr123** [comment]
I tried this but it didn't work ( ngrok)

في الأحد، 14 أوت 2022 12:52 bcoles ***@***.***> كتب:

**Comment by bcoles** [comment]
The same principle applies for portmap.io.

**Comment by Kayr123** [comment]
> 

Just tell me what to write please or what to put 
In the 2 pics i send you before

**Comment by bcoles** [comment]
Start BeEF, and ensure you can access the admin interface using the forwarded portmap.io URL: `https://your.portmap.io.url/ui/panel`

Once you've verified your portmap.io tunnel is configured correctly, you'll need to tell BeEF about the portmap.io host and port (BeEF only knows about its own local network interface IP addresses).

In order for the client-side BeEF JavaScript hook to be able to connect back to BeEF, the hook JavaScript needs to be generated with the correct connect-back details. The connect-back host, post and protocol (http/https), are configured in `beef.http.public:*` properties in the `config.yaml` configuration file. For example:


```yaml
beef:

    # ...

    http:

        # ...

        public: 
            host: "<your portmap.io host>" # public domain name for forwarding URL
            port: "443"                 # portmap port for forwarding URL (443 for HTTPS)
            https: true                 # true if portmap supports HTTPS, otherwise false
```
