### ISSUE TITLE
Need help with the setup of beEF with ngrok

### ISSUE THREAD

**Issue by P-SamiDev-Y** [beefproject/beef#2555]
Hello folks,

So after spending tons of time searching the web, forums, videos & the beEF documentation I can't seem to setup beEF with ngrok. Is there anybody out there that know how to do it and possibly guide me ?

I can provide any type of information if needed.

Thanks a lot!
Sami.

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

Where did you get stuck during troubleshooting?

**Comment by P-SamiDev-Y** [comment]
Pardon my late response, so I launch the terminal and I type `./ngrok http 3000`  :

![image](https://user-images.githubusercontent.com/73015114/187862385-8f23095d-6500-44e0-945c-a2636edc02c3.png)

As you can see the session is up and running proving that I have a valid Authtoken & Account that are connected.

But to be honest with you I don't know what to do after that. I believe I need to change something in the `ngrok.yml` or something like that. Here is my configuration file :

![image](https://user-images.githubusercontent.com/73015114/187864284-db8956e4-d42f-43e7-ba01-ca3bde518832.png)

So what do I do after ? Or is there anything needed to be done BEFORE that ? 

Thank you !

**Comment by bcoles** [comment]
> But to be honest with you I don't know what to do after that.

Modify the BeEF configuration file as per: https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

**Comment by P-SamiDev-Y** [comment]
Can tell me where is it located please ?

**Comment by bcoles** [comment]
> Can tell me where is it located please ?

In the root of the BeEF directory. If you've installed BeEF from an operating system package then the config file will be installed somewhere - likely `/etc/beef.yaml`.

**Comment by P-SamiDev-Y** [comment]
Is it `/etc/beef-xss/config.yml` ?

**Comment by P-SamiDev-Y** [comment]
Is it `/etc/beef-xss/config.yml` ?

**Comment by bcoles** [comment]
> Is it `/etc/beef-xss/config.yml` ?

It looks like this.

https://github.com/beefproject/beef/blob/master/config.yaml

**Comment by P-SamiDev-Y** [comment]
Oh so I got it right, I think it was just renamed. Now I will do what is said in the documentation. I'll come back to you once the modifications have been done :+1:

**Comment by P-SamiDev-Y** [comment]
Okayy so the thing is I believe I need to change the host as `<ngrok-id>.ngrok.io`. But sorry I don't get what is my ngrok ID. Where can I find it, in the dashboard ?

![Untitled design (3)](https://user-images.githubusercontent.com/73015114/187875847-3c4ab993-6be8-466d-a11b-323719d380fc.png)

**Comment by bcoles** [comment]
> Okayy so the thing is I believe I need to change the host as `<ngrok-id>.ngrok.io`.
> 
> ![Untitled design (3)](https://user-images.githubusercontent.com/73015114/187875847-3c4ab993-6be8-466d-a11b-323719d380fc.png)

No. Don't change the `host` where the arrow is pointed. Change the `public` properties as per the instructions.

> But sorry I don't get what is my ngrok ID. Where can I find it, in the dashboard ?

The ngrok host is printed to terminal when you start ngrok.

![image](https://user-images.githubusercontent.com/73015114/187862385-8f23095d-6500-44e0-945c-a2636edc02c3.png)

**Comment by P-SamiDev-Y** [comment]
Uhm I can't seem to find the public properties. Excuse me I am a little new to this

**Comment by P-SamiDev-Y** [comment]
For me, there seems to be a difference between the default config that you are giving me and the config that I have, but I'm still looking for the public properties

**Comment by bcoles** [comment]
> For me, there seems to be a difference between the default config that you are giving me and the config that I have, but I'm still looking for the public properties

Presumably you have installed BeEF from an operating system package. Refer to the documentation:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

Refer to the default config for an example:

https://github.com/beefproject/beef/blob/master/config.yaml

**Comment by P-SamiDev-Y** [comment]
Ok can point me exactly where and what I need to change please in the default config ?

**Comment by bcoles** [comment]
> Ok can point me exactly where and what I need to change please in the default config ?

Where did you get stuck?

**Comment by P-SamiDev-Y** [comment]
I got stuck when I needed to change the` config.yml` file. Since I can't find the public properties

**Comment by bcoles** [comment]
> I got stuck when I needed to change the `config.yml` file. Since I can't find the public properties

Add them.

**Comment by bcoles** [comment]
> Anywhere in the config file or at the end ?

Neither.

Where do the example configuration file and documentation say to put the `public` properties?

**Comment by P-SamiDev-Y** [comment]
After BeEF, HTTP I think ?

**Comment by bcoles** [comment]
Hint: The documentation offers this example:

```
beef:

    # ...

    http:

        # ...

        public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by default
```

**Comment by P-SamiDev-Y** [comment]
OOH I get it now, so if I'm following what you're saying, I'm going to copy-paste :

```
public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by default
```

After :

```
http:

        # ...
```

Right ?

**Comment by bcoles** [comment]
please try

**Comment by P-SamiDev-Y** [comment]
Like that ?

![image](https://user-images.githubusercontent.com/73015114/187890278-ab733034-9855-4ba6-ac0e-16dbf4018793.png)

**Comment by bcoles** [comment]
> Like that ?

No. Whitespace formatting and alignment is important. Like this:

```yaml
beef:

    # ...

    http:

        # ...

        public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by default
```
