### ISSUE TITLE
beef yaml.config error when setting ngrok http

### ISSUE THREAD

**Issue by hammad6981** [beefproject/beef#2775]
this error is cumming! 
whenever I try to edit public host and port this error appears.
10:12:07][!] Fatal Error: cannot load configuration file '/home/hmd6981/beef/./config.yaml' : (<unknown>): did not find expected key while parsing a block mapping at line 37 column 9
[10:12:07]    |   /usr/lib/ruby/3.1.0/psych.rb:455:in `parse'
[10:12:07]    |   /usr/lib/ruby/3.1.0/psych.rb:455:in `parse_stream'
[10:12:07]    |   /usr/lib/ruby/3.1.0/psych.rb:399:in `parse'
[10:12:07]    |   /usr/lib/ruby/3.1.0/psych.rb:324:in `safe_load'
[10:12:07]    |   /home/hmd6981/beef/core/main/configuration.rb:46:in `load'
[10:12:07]    |   /home/hmd6981/beef/core/main/configuration.rb:28:in `initialize'
[10:12:07]    |   ./beef:83:in `new'
[10:12:07]    |_  ./beef:83:in `<main>'

**Comment by bcoles** [comment]
Your changes to the configuration file are invalid.

The configuration file is in YAML formatting. Whitepsace and vertical alignment is important.

**Comment by stevenahoy** [comment]
are you delete # in public ? if yes put the # back , i got that error too

**Comment by bcoles** [comment]
Indentation is important.

This is correct:

```yaml
beef:
    # ...
    # ...
    # ...
    http:
        # ...
        # ...
        # ...
        public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by default
```

This is incorrect:

```yaml
beef:
    # ...
    # ...
    # ...
    http:
        # ...
        # ...
        # ...
         public: 
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by default
```
