### ISSUE TITLE
how to configure Beef-xss with Ngrok to exploit Beef on the internet

### ISSUE THREAD

**Issue by CONNEXAFR** [beefproject/beef#3141]
hi! can someone help me solve the problem that i have been struggling with for a while. i am a beginner in linux, i used several answers in several forums and some youtube tutorials to install kali linux on VM and install beef and Ngrok everything works perfectly. i can run beef locally and hook browsers without problem. i can also launch _ngrok http 80_ everything works perfectly well. my problem is at the level of port redirection or tunneling of beef-xss to allow it to hook a browser on over wan. 
![IMG_2117](https://github.com/user-attachments/assets/ee6b0379-5aae-4053-9a9d-2026e124237f)
i thank you in advance all your answers will be welcome. understood the level of my english, i just make the effort to make you understand what i have in heart 🥰 i come from a french speaking country in africa 🙏

**Comment by bcoles** [comment]
BeEF runs on port 3000 by default (not 80).

If you are running BeEF on port 3000:

```
ngrok http 3000
```

If you changed the default port and are running BeEF on port 80:

```
ngrok http 80
```

Ensure the `public*` settings your `config.yaml` file are set for your ngrok URL (where `<ngrok-id>` is `0aff......` from your screenshot):

```
beef:

    # ...

    http:

        # ...

        public:
            host: "<ngrok-id>.ngrok.io" # ngrok domain name for forwarding URL
            port: "443"                 # ngrok port for forwarding URL (443 for HTTPS)
            https: true                 # ngrok supports HTTPS by default
        allow_reverse_proxy: true
```

Refer to https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK
